apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"   
  name: grafana-ingress
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - '{{ .Values.global.host.grafana}}'
    secretName: san-app-tls  
  rules:
    - host: '{{ .Values.global.host.grafana}}'
      http:
        paths:
        - backend:
            service:
              name: loki-stack-grafana
              port:
                number: 80
          path: /
          pathType: Prefix
